version: '3.8'
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/soul-ai
      - NODE_ENV=development
      - JWT_SECRET=your_jwt_secret
      - JWT_EXPIRE=30d
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
